### ISSUE TITLE
import errors

### ISSUE THREAD

**Issue by v-yunbin** [pyannote/pyannote-metrics#38]
#### Description
install it on windows platform successfully,but met import errors in as follows:
```
python test_detection.py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Administrator\Anaconda3\lib\multiprocessing\spawn.py", line 105
, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\Administrator\Anaconda3\lib\multiprocessing\spawn.py", line 114
, in _main
    prepare(preparation_data)
  File "C:\Users\Administrator\Anaconda3\lib\multiprocessing\spawn.py", line 225
, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Administrator\Anaconda3\lib\multiprocessing\spawn.py", line 277
, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\Administrator\Anaconda3\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\Administrator\Anaconda3\lib\runpy.py", line 96, in _run_module_
code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\Administrator\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\Downloads\pyannote-metrics-master\pyannote-metric
s-master\tests\test_detection.py", line 6, in <module>
    from pyannote.metrics.detection import DetectionErrorRate
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "c:\users\administrator\anaconda3\lib\site-packages\pyannote.metrics-2.2-
py3.7.egg\pyannote\metrics\__init__.py", line 40, in <module>
  File "C:\Users\Administrator\Anaconda3\lib\multiprocessing\context.py", line 5
6, in Manager
    m.start()
  File "C:\Users\Administrator\Anaconda3\lib\multiprocessing\managers.py", line
543, in start
    self._process.start()
  File "C:\Users\Administrator\Anaconda3\lib\multiprocessing\process.py", line 1
12, in start
    self._popen = self._Popen(self)
  File "C:\Users\Administrator\Anaconda3\lib\multiprocessing\context.py", line 3
22, in _Popen
    return Popen(process_obj)
  File "C:\Users\Administrator\Anaconda3\lib\multiprocessing\popen_spawn_win32.p
y", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\Administrator\Anaconda3\lib\multiprocessing\spawn.py", line 143
, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\Administrator\Anaconda3\lib\multiprocessing\spawn.py", line 136
, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

**Comment by hbredin** [comment]
Unfortunately, `pyannote.metrics` does not support Windows.

However, you might want to try the advice reported in the error message: wrap everything in `if __name__ == '__main__:`

```python
if __name__ == '__main__':
    from pyannote.metrics.detection import DetectionErrorRate
```

See also related issue #34.

**Comment by EminSezgin** [comment]
> However, you might want to try the advice reported in the error message: wrap everything in `if __name__ == '__main__:`
> 
> ```python
> if __name__ == '__main__':
>     from pyannote.metrics.detection import DetectionErrorRate
> ```

I just tried this and it worked perfectly. (I'm on windows)
